fixes for worfkflow

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -32,14 +32,19 @@ jobs:
       - uses: actions/checkout@v2
       - uses: iffy/install-nim@v3
       - name: InstallLinuxDependencies
-          if: runner.os == 'Linux'
           run: |
-            sudo apt-get update
-            sudo apt install -y gcc npm libwebkit2gtk-4.0-dev curl python3
+            if [ "$RUNNER_OS" == "Linux" ]; then
+              sudo apt-get update && sudo apt install -y gcc npm libwebkit2gtk-4.0-dev curl python3
+              # export PATH=$HOME/.nimble/bin:$PATH
+            elif [ "$RUNNER_OS" == "Windows" ]; then
+              echo "no additional dependencies required
+            elif [ "$RUNNER_OS" == "macOS" ]; then
+              brew install boehmgc make sfml gtk+3
+              exit 1
+            fi
       # Runs a set of commands using the runners shell
       - name: Test
         run: |
-          export PATH=$HOME/.nimble/bin:$PATH
           nim --version
           echo y | nimble install -d
           nimble test
